version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - 3002:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: db
      MYSQL_PASSWORD: eero123
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: eero123
    ports:
      - "3003:80"
    depends_on:
      - db
    restart: always